# Generated by Django 3.2 on 2026-02-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cpu_cores',
            field=models.CharField(default='1 Core', help_text='CPU cores specification', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='ram_gb',
            field=models.IntegerField(default=1, help_text='RAM in GB'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_gb',
            field=models.IntegerField(default=10, help_text='Storage in GB'),
        ),
    ]
